name = "couple-album"
compatibility_date = "2026-05-25"
pages_build_output_dir = "client/build"

[vars]
TOKEN_SECRET = "replace-this-in-cloudflare-dashboard"

[[d1_databases]]
binding = "DB"
database_name = "couple-album-db"
database_id = "2487fac6-7276-4478-9f8f-6e4bcb901a10"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "couple-album-uploads"
